### ISSUE TITLE
Nil on encrypt on XCode 9.0

### ISSUE THREAD

**Issue by rredpoppy** [henrinormak/Heimdall#70] opened 2017-09-22 16:10 UTC
It seems that SecItemCopyMatching doesn't return a keyref. Having problems with SwiftyRSA key creation as well, was working before the XCode update. Relevant code:

```swift
guard let heimdall = Heimdall(
            publicTag: "sometag",
            publicKeyModulus: modulusData,
            publicKeyExponent: Data(bytes: [0, 1, 0, 1])) else {
                print("Could not obtain encryptor")
                return
        }
guard let cipher = heimdall.encrypt(someData) else {
            print("Could not encrypt data")
            return
        }
```

**Comment by henrinormak** [comment] 2018-09-21 06:12
Likely a duplicate of #46

**Closed as completed by henrinormak** 2018-09-21 06:12 UTC
